"""
Renderer for the H1 experiment results report.

Kept out of the script so the report text is importable and testable, and so the wording of
a negative or partial outcome cannot drift between runs.
"""

from __future__ import annotations

from typing import Any

EPISODES = ("yantian_2021", "baltimore_2024")


def render_h1_results(baseline: dict[str, Any], experimental: dict[str, Any],
                      decision: dict[str, Any]) -> str:
    lines: list[str] = []
    a = lines.append

    a("# H1 experiment results — vessel-queue stock vs frozen baseline")
    a("")
    a("> Generated by `python scripts/run_h1_experiment.py --write-report`. Acceptance "
      "criteria were fixed in [H1_EXPERIMENT_PROTOCOL.md](H1_EXPERIMENT_PROTOCOL.md) "
      "**before** these results existed, and are evaluated in code rather than in prose.")
    a("")

    a("## Headline")
    a("")
    a(f"**Verdict by the pre-registered rule: `{decision['verdict']}`** — four of the five "
      "criteria pass; criterion 1 fails.")
    a("")
    a("That label understates what happened, and the discrepancy is itself the most "
      "interesting result of this experiment. See [§7](#7-the-rule-and-its-flaw).")
    a("")

    a("## 1. What was changed")
    a("")
    a("```")
    a("BASELINE       port_capacity ──(linear, lag 0–1)──▶ shipping_delay")
    a("")
    a("EXPERIMENTAL   port_capacity ──(conservation)──▶ vessel_queue ──(linear, lag 0–1)──▶ shipping_delay")
    a("```")
    a("")
    a("One new variable, one edge replaced by two, one new axis. Everything downstream of "
      "`shipping_delay` is untouched, and every other edge keeps its polarity, effect range "
      "and lag exactly.")
    a("")
    a("**New variable** — `vessel_queue`, a stock in *normal-flow-weeks of unprocessed "
      "arrivals*. That unit was chosen because converting to vessels or TEU would need a "
      "conversion factor no data supports for these events.")
    a("")
    a("**New parameters** (three, one definitional):")
    a("")
    a("| Parameter | Value / range | Evidence status |")
    a("|---|---|---|")
    a("| arrivals (`inflow`) | 1.0, fixed | definitional — makes the queue exactly 0 in steady state |")
    a("| clearance surge | 1.05 / 1.15 / 1.35 | `expert_assumption`, swept |")
    a("| `vessel_queue → shipping_delay` | 0.08 / 0.15 / 0.25 | `expert_assumption`, swept |")
    a("")
    a("H1 being independently supported does **not** make these supported. They are "
      "assumptions with predeclared ranges, swept rather than fitted.")
    a("")

    a("## 2. Timing — the primary metrics")
    a("")
    a("| Event | Metric | Baseline | H1 | Delta | Interpretation |")
    a("|---|---|---|---|---|---|")
    labels = {"yantian_2021": "peak of `shipping_delay`",
              "baltimore_2024": "recovery milestone (`port_capacity`)"}
    for episode_id, row in decision["per_event"].items():
        interp = ("**improved**" if row["improvement_turns"] > 0 else
                  "unchanged (predicted)" if row["improvement_turns"] == 0 else "worse")
        a(f"| {episode_id} | {labels.get(episode_id, '')} | {row['baseline']:+d} "
          f"| {row['experimental']:+d} | {row['improvement_turns']:+d} | {interp} |")
    a(f"| — | **combined median** | {decision['baseline_combined_median']:+d} "
      f"| {decision['experimental_combined_median']:+d} "
      f"| {decision['combined_movement_toward_zero_turns']:+d} | below the ≥2 threshold |")
    a("")
    a("Baltimore's unchanged number is exactly what the protocol predicted in advance: its "
      "only scored milestone is on `port_capacity`, and H1 sits *downstream* of capacity. "
      "Capacity still relaxes back exactly as before, so that metric is mechanically "
      "incapable of moving. It is neither a success nor a failure of H1.")
    a("")

    a("## 3. Secondary metrics — Yantian")
    a("")
    b = baseline["per_event"]["yantian_2021"]["level"]
    e = experimental["per_event"]["yantian_2021"]["level"]
    a("| Metric | Baseline | H1 | Direction |")
    a("|---|---|---|---|")
    a(f"| Envelope coverage | {b['coverage_rate']:.2f} ({b['inside']}/{b['scored']}) "
      f"| **{e['coverage_rate']:.2f}** ({e['inside']}/{e['scored']}) | better |")
    a(f"| Peak magnitude error | {b['peak_magnitude_error']:+.2f} "
      f"| **{e['peak_magnitude_error']:+.2f}** | better |")
    a(f"| MAE | {b['mae']:.2f} | **{e['mae']:.2f}** | better |")
    a(f"| Normalised MAE | {b['normalized_mae']:.2f} | **{e['normalized_mae']:.2f}** | better |")
    a(f"| Correlation | {b['correlation']:+.3f} | **{e['correlation']:+.3f}** | better |")
    a(f"| Simulated peak | w{b['simulated_peak_turn']} | w{e['simulated_peak_turn']} "
      f"| closer to observed w{b['observed_peak_turn']} |")
    a(f"| Direction match | {b['direction_match']} | {e['direction_match']} | preserved |")
    a(f"| First divergence | w{b['first_divergence_turn']} | w{e['first_divergence_turn']} "
      "| unchanged — this is the no-hindsight baseline offset, not a dynamics failure |")
    a("")
    a("The correlation flip from **−0.15 to +0.69** is the most striking single number: the "
      "baseline's simulated path was mildly *anti*-correlated with what happened, and the "
      "queue-mediated path is strongly correlated with it.")
    a("")

    a("## 4. Does recovery slowness emerge, or was it imposed?")
    a("")
    a("It emerges. Nothing in the experimental module contains a recovery delay constant — a "
      "test asserts the absence of one.")
    a("")
    for episode_id in EPISODES:
        series = experimental["per_event"][episode_id]["series"]
        queue = series.get("vessel_queue")
        if not queue:
            continue
        capacity, delay = series["port_capacity"], series["shipping_delay"]
        recovered = next((t for t in range(2, len(capacity)) if capacity[t] >= 95.0), None)
        a(f"**{episode_id}**")
        a("")
        a(f"- queue starts accumulating once capacity drops, peaks at **{max(queue):.2f} "
          f"flow-weeks in week {queue.index(max(queue))}**")
        a(f"- capacity is back above 95% in **week {recovered}** — and the queue is still "
          f"**{queue[recovered]:.2f}** at that moment")
        a(f"- `shipping_delay` therefore peaks later, in **week {delay.index(max(delay))}**")
        a(f"- the queue is still draining at the end of the window ({queue[-1]:.2f})")
        a("")
    a("This is the mechanism doing exactly what H1 says it should: *a reopened port is not a "
      "cleared queue*.")
    a("")

    a("## 5. Failure modes and unexpected behaviour")
    a("")
    a("- **The queue does not fully clear inside either window.** With central clearance "
      "surge (1.15) the drain rate is only 15% of nominal throughput per week, so a two-week "
      "backlog takes many weeks to work off. This is reported rather than tuned away: the "
      "surge range was predeclared, and shortening the drain by raising it would be exactly "
      "the retuning this experiment forbids.")
    a("- **Yantian's first divergence is unchanged at week 0**, because it comes from the "
      "no-hindsight baseline (the only admissible pre-cutoff value was 0.30 days above the "
      "actual May level). No dynamics change can fix an initial-condition offset.")
    a("- **No magnitude blow-up appeared**, which was a live risk: replacing the direct "
      "capacity→delay edge with a queue-mediated path could have over- or under-shot. It "
      "undershot slightly less than the baseline overshot.")
    a("")

    a("## 6. Anti-retuning confirmation")
    a("")
    a("- One shared configuration across both events — the same module, the same swept grid. "
      "Per-event parameter values are impossible by construction and are asserted by a test.")
    a("- No baseline coefficient, lag, polarity, baseline level, scale or response changed; "
      "the frozen-module regression tests still pass.")
    a("- The baseline replay reports reproduce identically.")
    a("- H2 was not implemented: `order_backlog` is still a relaxation variable, and no "
      "downstream lag or effect range moved.")
    a("")

    a("## 7. The rule, and its flaw")
    a("")
    a("| Criterion | Result |")
    a("|---|---|")
    for name, ok in decision["criteria"].items():
        a(f"| {name.replace('_', ' ')} | {'PASS' if ok else '**FAIL**'} |")
    a("")
    a("Criterion 1 gated on the **combined median** timing bias. With only two scored tests "
      "— one of which the protocol itself predicted would be mechanically frozen — the median "
      "of {−5, −6} is −5, so a 4-turn improvement on the only metric that could move shows up "
      "as a 1-turn movement in the aggregate.")
    a("")
    a("**That was a bad choice of aggregator, and it was my own.** The protocol correctly "
      "predicted Baltimore's insensitivity and then still gated on a statistic that averages "
      "it in. The rule is nonetheless applied as written: changing an acceptance criterion "
      "after seeing results would destroy the only thing pre-registration is for.")
    a("")
    a("The correct response is to fix the aggregator **for the next experiment, in advance** "
      "— e.g. gate on the median over *mechanically sensitive* tests only, declared per "
      "experiment — not to re-score this one.")
    a("")

    a("## 8. Verdict")
    a("")
    a(f"### `{decision['verdict']}` by the pre-registered rule")
    a("")
    a("The substantive finding, stated plainly and separately from the label:")
    a("")
    a("> **An independently supported queue-stock mechanism explains a substantial part of "
      "the simulator's timing bias on the only event able to test it** — peak timing error "
      "−9 → −5 weeks, peak magnitude error +3.3 → +1.4, envelope coverage 0.00 → 0.50, "
      "correlation −0.15 → +0.69 — **while leaving the second event's metric untouched, as "
      "predicted, because that metric cannot see the mechanism.**")
    a("")
    a("So the answer to the task's question — *does an independently supported queue-stock "
      "mechanism explain part of the previously measured timing bias?* — is **partially, on "
      "the evidence available**, and the evidence available is one event.")
    a("")

    a("## 9. Consequences")
    a("")
    a("| Item | Status after this experiment |")
    a("|---|---|")
    a("| H1 hypothesis | `experimental_no_effect` by the rule; substantive improvement recorded |")
    a("| Known defect *recovery dynamics too fast* | stays **`known`** — not `mitigated` |")
    a("| Default production model | **unchanged**. Do not merge. |")
    a("| Historical validation | still blocked — needs a held-out event |")
    a("")
    a("**The evidence does not yet support changing the default production model.** One event "
      "moved; one could not. Promoting a mechanism on a single sensitive observation would "
      "repeat the mistake this project has already documented twice.")
    a("")

    a("## 10. Next step")
    a("")
    a("1. Pre-register a better aggregator (sensitivity-weighted) for the next experiment.")
    a("2. Find an event whose *downstream* metric can move — the same event #3 problem, now "
      "with a sharper requirement: it must have a delay or queue observation, not just a "
      "capacity milestone.")
    a("3. Only then can H1 be evaluated out of sample and the defect move to `mitigated` and "
      "eventually `historically_validated`.")
    return "\n".join(lines)
