#!/usr/bin/env python3
"""
H1 falsification test: does a real port queue behave like a stock?

    python scripts/test_queue_mechanism.py
    python scripts/test_queue_mechanism.py --write-report

Runs entirely on independently sourced observations. **No simulation is involved** — the
Event Simulator is not imported, no world is run, and no coefficient is touched. The point
is to find out whether a structural hypothesis is consistent with how the real system
behaves, before spending a held-out event on it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        try:
            _stream.reconfigure(encoding="utf-8", errors="replace")
        except (ValueError, OSError):
            pass

from event_sim.mechanism import compare_candidates, load_queue_series  # noqa: E402

REPORTS_DIR = _PROJECT_ROOT / "docs" / "replays"
DEFAULT_SERIES = "socal_queue_2021"


def render_console(result: dict) -> str:
    out: list[str] = []
    rule = lambda t: f"\n{t}\n{'-' * len(t)}"  # noqa: E731

    out.append(f"H1 MECHANISM TEST — {result['title']}")
    out.append(f"series={result['series']}  n={result['n_observations']}  (no simulation involved)")

    out.append(rule("CANDIDATE FORMS"))
    for name, formula in result["candidates"].items():
        out.append(f"  {name:<12} {formula}")

    shape = result["shape"]
    out.append(rule("SHAPE DIAGNOSTIC (no fitting, no parameters)"))
    out.append(f"  observed    : {[int(v) for v in shape['values']]}")
    out.append(f"  increments  : {[int(v) for v in shape['increments']]}")
    out.append(f"  decaying?   : {shape['increments_decaying']}")
    out.append(f"  -> {shape['verdict']}")
    out.append(f"  {shape['reasoning']}")

    out.append(rule("FIT COMPARISON"))
    relax, stock = result["relaxation_fit"], result["stock_fit"]
    out.append(f"  relaxation (2 params: r, P)   r={relax['r']:.2f} P={relax['driver_constant']:.0f}")
    out.append(f"    predicted : {[round(v, 1) for v in relax['predicted']]}")
    out.append(f"    SSE={relax['sse']:.1f}  RMSE={relax['rmse']:.2f}")
    out.append(f"  stock      (1 param: k)       k={stock['net_imbalance_per_period']:.1f} per period")
    out.append(f"    predicted : {[round(v, 1) for v in stock['predicted']]}")
    out.append(f"    SSE={stock['sse']:.1f}  RMSE={stock['rmse']:.2f}")
    ratio = result["sse_ratio_relaxation_over_stock"]
    if ratio:
        out.append(f"  relaxation SSE is {ratio:.2f}x the stock SSE, with one MORE free parameter")

    out.append(rule("IMPLIED DRIVER (the decisive check — needs no fit)"))
    for label, implied in result["implied_driver"].items():
        out.append(f"  {label}: {implied['claim']}")
    ctx = result["driver_context"]
    if ctx:
        out.append(f"  Actual driver: {ctx.get('claim', '')}")
        figures = ctx.get("figures_attributed_to_port_of_los_angeles_releases", {})
        if figures:
            out.append("    " + "  ".join(f"{k}={v:,}" for k, v in sorted(figures.items())))
        out.append(f"    provenance: {ctx.get('provenance_tier', '')}")

    out.append(rule("VERDICT"))
    out.append(f"  {result['verdict']}")
    out.append(f"  {result['reason']}")

    out.append(rule("LIMITATIONS"))
    for item in result["limitations"]:
        out.append(f"  - {item}")
    out.append(rule("EXCLUDED OBSERVATIONS (definitional inconsistency)"))
    for item in result["excluded_observations"]:
        out.append(f"  - {item['value']} on {item.get('date', '?')}: {item['reason']}")

    out.append("")
    out.append(result["framing"])
    return "\n".join(out)


def render_report(result: dict) -> str:
    lines: list[str] = []
    a = lines.append
    shape = result["shape"]
    relax, stock = result["relaxation_fit"], result["stock_fit"]

    a("# H1 mechanism test — does a real port queue behave like a stock?")
    a("")
    a("> Generated by `python scripts/test_queue_mechanism.py --write-report`. "
      "**No simulation is involved.** The Event Simulator is not imported, no world is run, "
      "and no coefficient was changed.")
    a("")
    a("## Why test a mechanism instead of running a third replay")
    a("")
    a("Two historical replays established that the model recovers too early "
      "([cross-event diagnosis](CROSS_EVENT_DIAGNOSIS.md)), and a third event with the "
      "required local time series could not be sourced "
      "([event #3 search](EVENT3_SEARCH.md)). But the leading explanation — H1, that a queue "
      "is a **stock** that integrates an imbalance rather than a variable that relaxes toward "
      "pressure — is a claim about how the real world works. It can be tested directly, on "
      "independent data, without any simulation at all.")
    a("")
    a("That is a cheaper and stronger test: if H1 fails here, it should be deleted rather "
      "than carried forward into an expensive held-out experiment.")
    a("")
    a("## The two candidate forms")
    a("")
    a("| Form | Law | Where it comes from |")
    a("|---|---|---|")
    a("| Relaxation | `q(t+1) = q(t) + r·(P(t) − q(t))` | what the engine does today |")
    a("| Stock (H1) | `q(t+1) = q(t) + (A(t) − C)`, clipped at 0 | the hypothesis |")
    a("")
    a("They are separable **from the shape of the queue alone**: under a steady driver, "
      "relaxation closes a fixed fraction of a shrinking gap each period, so its increments "
      "must decay geometrically. A stock with a steady imbalance grows linearly.")
    a("")
    a(f"## Data — {result['title']}")
    a("")
    a(f"{result['definition']}")
    a("")
    a("| Month | Ships at anchor | Increment |")
    a("|---|---|---|")
    values, increments = shape["values"], [None] + shape["increments"]
    periods = ["2021-06", "2021-07", "2021-08", "2021-09", "2021-10"]
    for period, value, inc in zip(periods, values, increments):
        a(f"| {period} | {int(value)} | {'—' if inc is None else f'+{int(inc)}'} |")
    a("")
    a("Single source, single measurement definition. Points reported elsewhere under other "
      "definitions were **excluded rather than spliced**:")
    a("")
    for item in result["excluded_observations"]:
        a(f"- **{item['value']}** ({item.get('date', '?')}) — {item['reason']}")
    a("")

    a("## Result 1 — shape (no fitting, no parameters)")
    a("")
    a(f"Increments: **{', '.join('+' + str(int(i)) for i in shape['increments'])}** — "
      f"non-decaying, in fact growing.")
    a("")
    a(f"> {shape['verdict']}")
    a("")
    a(shape["reasoning"])
    a("")

    a("## Result 2 — fit comparison")
    a("")
    a("| Form | Free parameters | Fitted | Predicted | SSE | RMSE |")
    a("|---|---|---|---|---|---|")
    a(f"| Relaxation | 2 (r, P) | r={relax['r']:.2f}, P={relax['driver_constant']:.0f} "
      f"| {[round(v, 1) for v in relax['predicted']]} | {relax['sse']:.1f} | {relax['rmse']:.2f} |")
    a(f"| Stock | 1 (k) | k={stock['net_imbalance_per_period']:.1f}/month "
      f"| {[round(v, 1) for v in stock['predicted']]} | {stock['sse']:.1f} | {stock['rmse']:.2f} |")
    a("")
    ratio = result["sse_ratio_relaxation_over_stock"]
    a(f"Relaxation's error is **{ratio:.2f}× the stock form's, with one more free parameter**. "
      "Its best fit necessarily undershoots the late points, because it must decelerate as "
      "the queue approaches its fitted driver.")
    a("")

    a("## Result 3 — the implied driver (the decisive check)")
    a("")
    a("This is the strongest part of the test, because it requires no fit at all — only "
      "arithmetic and the public record. Inverting the relaxation law gives the driver that "
      "would have had to exist:")
    a("")
    a("| Assumed response rate | Implied driver growth over Jun–Oct 2021 |")
    a("|---|---|")
    for label, implied in result["implied_driver"].items():
        growth = implied["implied_driver_growth_factor"]
        a(f"| {label} | **~{growth:.1f}×** |")
    a("")
    ctx = result["driver_context"]
    a(f"**What the driver actually did:** {ctx.get('claim', '')}")
    a("")
    figures = ctx.get("figures_attributed_to_port_of_los_angeles_releases", {})
    if figures:
        a("| Month | Loaded import TEU |")
        a("|---|---|")
        for month, value in sorted(figures.items()):
            a(f"| {month} | {value:,} |")
        a("")
    a(f"> **Provenance caveat:** {ctx.get('provenance_note', '')}")
    a("")
    a("So relaxation requires a roughly threefold rise in the driver over exactly the months "
      "when the driver was flat. **That is not a close call, and it does not depend on the "
      "exact figures.**")
    a("")

    a("## Verdict")
    a("")
    a(f"### {result['verdict']}")
    a("")
    a(f"{result['reason']}.")
    a("")
    a("The verdict rule is deliberately conservative: `H1 SUPPORTED` requires **both** that "
      "the stock form fits better **and** that the shape is structurally incompatible with "
      "relaxation. A better fit alone would not be enough — an extra parameter can always buy "
      "some fit, and here the stock form has *fewer* parameters, not more.")
    a("")

    a("## What this does and does not establish")
    a("")
    a("**Does establish:** a real port queue, measured independently of this project, "
      "accumulates like a stock. H1 is no longer merely plausible — it is consistent with "
      "observed behaviour, and its rival is not.")
    a("")
    a("**Does not establish:** that adding a queue stock will fix the model's timing bias. "
      "That is a different claim and still requires calibrating on one event and evaluating "
      "on a **held-out** event, which cannot begin until a third event exists.")
    a("")
    a("The test also cannot speak to **hysteresis**. The drain phase was measured under a "
      "different definition after the queuing regime changed in November 2021, so onset and "
      "recovery cannot be compared on a consistent basis here.")
    a("")

    a("## Limitations")
    a("")
    for item in result["limitations"]:
        a(f"- {item}")
    a("")

    a("## Consequence for the roadmap")
    a("")
    a("1. ~~H1 mechanistic test~~ — **done, H1 supported**.")
    a("2. H1 is *not* deleted; it advances to experimental implementation as an alternative "
      "module, leaving `world_models/supply_chain/port_disruption.json` untouched.")
    a("3. H2 (`order_backlog` as a true stock) should get the same treatment: it is the same "
      "structural claim one layer downstream, and the same kind of test would apply.")
    a("4. Calibrate on one event → freeze → evaluate on a held-out event. Still blocked on "
      "event #3.")
    a("5. Only after out-of-sample success does the main topology change.")
    a("")
    a("The Known Model Defect stays on the product surface throughout, moving "
      "`known → mitigated → historically_validated` rather than being deleted, so the "
      "model's scientific history remains visible.")
    return "\n".join(lines)


def render_h2_console(result: dict) -> str:
    out: list[str] = []
    rule = lambda t: f"\n{t}\n{'-' * len(t)}"  # noqa: E731
    h, p = result["hysteresis"], result["persistence"]

    out.append(f"H2 MECHANISM TEST — {result['title']}")
    out.append(f"series={result['series']}  n={result['n_months']} months  (no simulation involved)")
    out.append(f"\nPrediction stated before testing: {result['prediction_stated_before_testing']}")

    out.append(rule("CIRCULARITY GUARD"))
    out.append(f"  {result['circularity_warning']}")

    out.append(rule("HYSTERESIS — the decisive test (detrended, one cycle)"))
    cycle = h["cycle"]
    out.append(f"  cycle: {cycle['pressure_trough']} ({cycle['pressure_trough_value']:.1f}%) "
               f"-> {cycle['pressure_peak']} ({cycle['pressure_peak_value']:.1f}%)")
    out.append(f"  secular trend removed: {h['cover_trend_per_month']:+.5f} months of cover per month")
    for row in h["bins"]:
        if row.get("gap") is None:
            out.append(f"  CU {row['bin'][0]}-{row['bin'][1]}%: {row['note']}")
            continue
        out.append(
            f"  CU {row['bin'][0]}-{row['bin'][1]}%  up {row['up_mean_detrended_cover']:+.4f} "
            f"(n={row['n_up']})   down {row['down_mean_detrended_cover']:+.4f} (n={row['n_down']})"
            f"   gap {row['gap']:+.4f}   supports H2: {row['supports_h2']}"
        )
    out.append(f"  mean gap {h['mean_gap']:+.4f}  ->  supports H2: {h['supports_h2']}")

    out.append(rule("PERSISTENCE — the same question WITHOUT trend control"))
    if p.get("returned_to_baseline_pressure"):
        out.append(f"  pressure {p['baseline_pressure']:.1f}% ({p['baseline_month']}) "
                   f"-> {p['return_pressure']:.1f}% ({p['return_month']})")
        out.append(f"  cover {p['baseline_cover']:.3f} -> {p['cover_at_return']:.3f} "
                   f"(x{p['cover_ratio_vs_baseline']:.2f})   supports H2: {p['supports_h2']}")
        out.append("  NOTE: this comparison is NOT detrended. It disagrees with the")
        out.append("  hysteresis test above, and the difference IS the secular trend.")

    out.append(rule("VERDICT"))
    out.append(f"  {result['verdict']}")
    out.append(f"  {result['reason']}")

    out.append(rule("LIMITATIONS"))
    for item in result["limitations"]:
        out.append(f"  - {item}")
    out.append("")
    out.append(result["framing"])
    return "\n".join(out)


def render_h2_report(result: dict) -> str:
    lines: list[str] = []
    a = lines.append
    h, p = result["hysteresis"], result["persistence"]

    a("# H2 mechanism test — does a real order backlog behave like a stock?")
    a("")
    a("> Generated by `python scripts/test_queue_mechanism.py --h2 --write-report`. "
      "**No simulation is involved.** No coefficient was changed.")
    a("")
    a("## Why H2 needs a different test from H1")
    a("")
    a("[H1 was supported](H1_QUEUE_MECHANISM.md) by an increment-shape argument: that queue "
      "had a clean build phase under a flat driver, and relaxation is *structurally* barred "
      "from producing non-decaying increments under a steady driver.")
    a("")
    a("A backlog gives no such clean phase — its driver moves throughout, so shape alone is "
      "ambiguous. The distinctive signature of a stock is instead **path dependence**:")
    a("")
    a("| Form | Prediction |")
    a("|---|---|")
    a("| Relaxation | backlog is a function of CURRENT pressure — same pressure, same backlog |")
    a("| Stock (H2) | backlog is the INTEGRAL of past imbalances — same pressure, different backlog depending on the path |")
    a("")
    a(f"So the decisive test is hysteresis, and the prediction was stated before testing: "
      f"**{result['prediction_stated_before_testing']}**.")
    a("")

    a("## Two traps this test had to avoid")
    a("")
    a("**1. Circularity.**")
    a("")
    a(f"> {result['circularity_warning']}")
    a("")
    a("Verified empirically: the identity holds to about 1.1% median relative error, so New "
      "Orders is effectively a derived quantity. Federal Reserve capacity utilisation is used "
      "as the pressure variable instead — measured by a different agency, with no accounting "
      "relationship to unfilled orders.")
    a("")
    a("**2. Trend masquerading as hysteresis.** Backlog cover trends upward across the "
      "window, so an uncontrolled matched-pressure comparison across years measures the trend "
      "rather than path dependence. Cover is linearly detrended and the comparison restricted "
      "to a single capacity-utilisation cycle.")
    a("")

    a(f"## Data — {result['title']}")
    a("")
    a(result["definition"])
    a("")
    a("US Census M3 and Federal Reserve G.17 series, retrieved via FRED. **Public domain, so "
      "the series are stored in this repository** — the first fully redistributable data in "
      "the project.")
    a("")

    a("## Result 1 — hysteresis (detrended, within one cycle)")
    a("")
    cycle = h["cycle"]
    a(f"Cycle: pressure trough **{cycle['pressure_trough']}** "
      f"({cycle['pressure_trough_value']:.1f}%) → peak **{cycle['pressure_peak']}** "
      f"({cycle['pressure_peak_value']:.1f}%). Secular trend removed: "
      f"{h['cover_trend_per_month']:+.5f} months of cover per month.")
    a("")
    a("| Capacity utilisation | Up-leg (detrended cover) | Down-leg | Gap | Supports H2? |")
    a("|---|---|---|---|---|")
    for row in h["bins"]:
        if row.get("gap") is None:
            a(f"| {row['bin'][0]}–{row['bin'][1]}% | — | — | — | {row['note']} |")
            continue
        a(f"| {row['bin'][0]}–{row['bin'][1]}% | {row['up_mean_detrended_cover']:+.4f} "
          f"(n={row['n_up']}) | {row['down_mean_detrended_cover']:+.4f} (n={row['n_down']}) "
          f"| **{row['gap']:+.4f}** | {'yes' if row['supports_h2'] else '**no**'} |")
    a("")
    a(f"Mean gap **{h['mean_gap']:+.4f}** — the wrong sign. At matched capacity utilisation, "
      "backlog cover was *lower* on the way down than on the way up, which is the opposite of "
      "what a stock predicts.")
    a("")

    a("## Result 2 — the same question without trend control")
    a("")
    if p.get("returned_to_baseline_pressure"):
        a(f"Pressure returned to its starting level ({p['baseline_pressure']:.1f}% in "
          f"{p['baseline_month']} → {p['return_pressure']:.1f}% in {p['return_month']}), and "
          f"backlog cover over the same span went "
          f"**{p['baseline_cover']:.3f} → {p['cover_at_return']:.3f}** "
          f"(×{p['cover_ratio_vs_baseline']:.2f}).")
        a("")
        a("Taken at face value that is a **+28% persistent backlog** and looks like strong "
          "support for H2. It is not: this comparison is not detrended, and the entire gap is "
          "the secular trend that the controlled test removes.")
        a("")
        a("**The two tests disagree, and the disagreement is the finding.** The uncontrolled "
          "version would have promoted H2 on an artefact.")
    a("")

    a("## Verdict")
    a("")
    a(f"### {result['verdict']}")
    a("")
    a(f"{result['reason']}.")
    a("")

    a("## What this does and does not establish")
    a("")
    a("**Does establish:** in national aggregate manufacturing data, an order backlog does "
      "not show the path dependence a stock predicts, once the secular trend is removed.")
    a("")
    a("**Does not establish that H2 is wrong.** The test is *underpowered for the claim*: the "
      "model's `order_backlog` is a node-level, disruption-specific backlog, while this series "
      "aggregates every US manufacturing industry — averaging together sectors that are "
      "accumulating and sectors that are draining. That is precisely the kind of averaging "
      "that would hide a node-level stock.")
    a("")
    a(f"> {result['framing']}")
    a("")
    a("**H2 is therefore marked `not_supported`, not `rejected`, and is not deleted.**")
    a("")

    a("## A definitional problem this test exposed in the model")
    a("")
    a("`order_backlog` is currently described as *\"unfulfilled orders queued behind the "
      "disruption, including cargo waiting at anchor\"* — which conflates two different "
      "things with different dynamics and different observability:")
    a("")
    a("| Thing | Dynamics | Observability | Evidence |")
    a("|---|---|---|---|")
    a("| Cargo physically waiting at the port | integrates (H1) | proxy-observable | **supported** |")
    a("| Unfulfilled customer orders in the order book | not shown to integrate (H2) | latent at node level | **not supported** |")
    a("")
    a("One variable cannot carry both. Splitting them is a candidate structural change in its "
      "own right — and note it would be a change made for a *definitional* reason, not to "
      "improve a fit.")
    a("")

    a("## Limitations")
    a("")
    for item in result["limitations"]:
        a(f"- {item}")
    a("")

    a("## Consequence for the roadmap")
    a("")
    a("1. H1 — **independently supported**, may proceed to experimental implementation.")
    a("2. H2 — **not supported at this resolution**, does not proceed, is not deleted.")
    a("3. The topology sketch `queue_stock → delay → backlog_stock → inventory → service` is "
      "**half-supported**: the queue leg has independent evidence, the backlog leg does not. "
      "Building both at once would smuggle an untested mechanism in behind a tested one.")
    a("4. To test H2 properly, a node-level backlog series is needed — the same procurement "
      "problem as [event #3](EVENT3_SEARCH.md), and the same class of customer data that "
      "would ground the model's latent downstream half.")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("series", nargs="?", default=None)
    parser.add_argument("--h2", action="store_true", help="run the H2 backlog test instead of H1")
    parser.add_argument("--write-report", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    if args.h2:
        from event_sim.mechanism import compare_h2, load_backlog_series

        series = load_backlog_series(args.series or "us_manufacturing_backlog")
        result = compare_h2(series)
        print(json.dumps(result, indent=2, default=str) if args.json else render_h2_console(result))
        if args.write_report:
            REPORTS_DIR.mkdir(parents=True, exist_ok=True)
            path = REPORTS_DIR / "H2_BACKLOG_MECHANISM.md"
            path.write_text(render_h2_report(result) + "\n", encoding="utf-8")
            print(f"\nReport written to {path.relative_to(_PROJECT_ROOT)}")
        return 0

    bundle = load_queue_series(args.series or DEFAULT_SERIES)
    result = compare_candidates(bundle)

    if args.json:
        print(json.dumps(result, indent=2, default=str))
    else:
        print(render_console(result))

    if args.write_report:
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        path = REPORTS_DIR / "H1_QUEUE_MECHANISM.md"
        path.write_text(render_report(result) + "\n", encoding="utf-8")
        print(f"\nReport written to {path.relative_to(_PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
